name = "gwins-md"
main = "src/index.ts"
compatibility_date = "2026-02-15"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "gwins-md"

[[d1_databases]]
binding = "DB"
database_name = "gwins-md"
database_id = "0bf8c2cf-7ece-4533-8447-086732bbfd74"

[[vectorize]]
binding = "VEC"
index_name = "gwins-md-chunks"

[[queues.producers]]
binding = "TRACE_QUEUE"
queue = "gwins-trace-queue"

[[queues.consumers]]
queue = "gwins-trace-queue"
max_batch_size = 5
max_batch_timeout = 5
max_retries = 2

[triggers]
crons = ["0 * * * *"]
